### PR TITLE
Adding UDP multicast example

### PR DESCRIPTION
**Pull request by zigster64**
- Add simple UDP listener
- On each socket, store 'connected_to' and 'bound_to' endpoints

### CODE REVIEW

**Comment by zigster64** [comment]
Tested on :
- FreeBSD
- Linux
- Mac OSX

Not tested on:
- Windows

**Comment by MasterQ32** [comment]
Nice PR! Can you add `udp-examples` to the CI file in `.github`?

**Comment by zigster64** [comment]
Will add the CI additions.

May as well hang in there for a bit, found some problems with my own pr, and adding some better examples and cleaner code.

Getting the hang of it now.

**Comment by MasterQ32** [comment]
You tell me when you're ready for merge :)

**Comment by zigster64** [comment]
Cool. 

Might just add some udp stuff to the test suite for coverage, and that should do. 

Tomorrow then. Zzzzz time here.

**Comment by zigster64** [comment]
That should do, thanks

Added an interesting test setup for UDP, but it kept flaking on CI - different fails each time.  So removed that.

Looks good on local for BSD/Linux/Mac

cheers

**Comment by MasterQ32** [comment]
Very cool, thank you!

**Pull request merged**
