### PR TITLE
Windows async support

### PR DESCRIPTION
**Pull request by alexnask**
For now I'm only aiming to make the recv and send function async compatible.  
For connect, accept etc. we need changes to the standard loop for sure.

### CODE REVIEW

**Comment by alexnask** [comment]
This is modelled after how ReadFile works in the standard library.

**Comment by alexnask** [comment]
Here is Andrew's pro chat adapted to zig-network  
Works fine at least in localhost on windows :-)

```
const std = @import("std");
const network = @import("network.zig");

pub const io_mode = .evented;

pub fn main() anyerror!void {
    const allocator = std.heap.page_allocator;

    try network.init();
    defer network.deinit();

    var server = try network.Socket.create(.ipv4, .tcp);
    defer server.close();

    try server.bind(.{
        .address = .{ .ipv4 = network.Address.IPv4.any },
        .port = 0,
    });

    try server.listen();
    std.debug.warn("listening at {}\n", .{try server.getLocalEndPoint()});

    var room = Room{ .clients = std.AutoHashMap(*Client, void).init(allocator) };

    while (true) {
        const client = try allocator.create(Client);
        client.* = Client{
            .conn = try server.accept(),
            .handle_frame = async client.handle(&room),
        };
        try room.clients.putNoClobber(client, {});
    }
}
const Client = struct {
    conn: network.Socket,
    handle_frame: @Frame(handle),

    fn handle(self: *Client, room: *Room) !void {
        try self.conn.outStream().writeAll("server: welcome to teh chat server\n");
        while (true) {
            var buf: [100]u8 = undefined;
            const amt = try self.conn.receive(&buf);
            const msg = buf[0..amt];
            room.broadcast(msg, self);
        }
    }
};
const Room = struct {
    clients: std.AutoHashMap(*Client, void),

    fn broadcast(room: *Room, msg: []const u8, sender: *Client) void {
        var it = room.clients.iterator();
        while (it.next()) |entry| {
            const client = entry.key;
            if (client == sender) continue;
            client.conn.outStream().writeAll(msg) catch |e| std.debug.warn("unable to send: {}\n", .{e});
        }
    }
};
```

**Comment by MasterQ32** [comment]
Is this ready to merge?

**Comment by alexnask** [comment]
I think so, I will revisit this to make the other calls non blocking at some point.

**Pull request merged**
